version: '3.8'
services:
  usersDatabase:
    image: postgres:latest
    container_name: users_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: ForkFinder
    volumes:
      - users_db_data:/var/lib/postgresql/data
  sessionDatabase:
    image: mongo:latest
    container_name: session_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
      image: redis:7-alpine
      container_name: restraunt_redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      command: redis-server --appendonly yes --requirepass redispassword
      environment:
        - REDIS_PASSWORD=redispassword

volumes:
  redis_data:
  mongodb_data:
  users_db_data:
