@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(iau, "Indivdual App User", "A user of the app.")
System_Ext(es, "E-mail system", "The external e-mail system.")
System_Ext(rds, "Restraunt Data System", "The external system for getting restraunt data.")
System_Boundary(ibs, "Restraunt Finder") {
    Container(ma, "Mobile App", "React Native", "Provides the user interface for creating sessions with people and swiping to find restraunts.")
    Container(db, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
    Container(nrdb, "Database", "Non Relational Database", "Stores the user session information, such as session preferences and connected users")
    Container(cache, "Cache", "Cache Storage", "Stores the restraunt information based on the session preferences")
    Container(api, "API Application", "Typescript and Nest.js MVC", "Provides user and restraunt finding functionality via a JSON/HTTP API.")

    Rel(api, es, "Sends e-mails", "SMTP")
    Rel(api, rds, "Uses", "JSON/HTTPS")
    Rel(api, db, "Reads & writes to", "TypeORM")
    Rel(api, nrdb, "Reads & writes to", "TypeORM")
    Rel(api, cache, "Reads & writes to", "Redis")
    Rel(ma, api, "Uses", "JSON/HTTPS")
}

Rel(iau, wa, "Uses", "HTTPS")
Rel(iau, ma, "Uses")
Rel(es, iau, "Sends e-mails to")
@enduml
